# Generated by Django 5.0.6 on 2024-06-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='repost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='repost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='share',
            name='post',
        ),
        migrations.RemoveField(
            model_name='share',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Repost',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
