# Generated by Django 5.0.6 on 2024-06-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0002_remove_like_post_remove_like_user_remove_repost_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
